### ISSUE TITLE
Разработка драйвера датчика усилия привода руля

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#10]
Помимо положение также необходимо определять усилие привода руля, дабы его не перегрузить

**Comment by DenF2412** [comment]
@KaiL4eK эту задачу можно разбить на несколько:
1. Оценить усилие от привода к рулевому механизму можно в нашем случае только с помощью датчика тока.
2. По датчику момента, который встроен в привод можно оценить на сколько сильно сопротивляется оператор совершению маневра. Если вдруг оператор пытается изменить траекторию, но почему-то не нажал на тормоз, то превышение порогового значения (определяется экспериментально) может свидетельствовать, что необходимо перевести в режим ручного управления.

**Comment by KaiL4eK** [comment]
@DenF2412 если я правильно понял из ответа, в рулевом механизме два датчика?

**Comment by KaiL4eK** [comment]
@DenF2412 и все таки?) Датчика получается два в руле?)

**Comment by KaiL4eK** [comment]
Перенесено в #3, присваиваю nonfix
