### ISSUE TITLE
Запуск симулятора робота с лидаром.

### ISSUE THREAD

**Issue by Alakeyska** [lsd-maddrive/tigra-project#114]
Самостоятельно написать запуск симулятора. 
- Использовать модель с лидаром. 
- Настроить автономную навигацию с помощью лидара.
- Разобраться с costmap, как настраивать и выяснить почему робот не уезжает дальше 20 метров (может потребоваться помощь Кирилла).
- Gazebo запускать без GUI (headless).

**Comment by KaiL4eK** [comment]
@Alakeyska  закрываем?

**Comment by Alakeyska** [comment]
Закрываем. В любом случае я залил последнюю версию. Если надо, можно доделать в будущем.
