### ISSUE TITLE
Переход модуля управления драйвером приводов на новое железо

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#13]
Доработать существующий модуль управления драйвером приводов в соответствии с требованиями.

**Comment by KaiL4eK** [comment]
Нус, что конкретно надо сделать?) Или сейчас этот issue висит в ожидании понимания конечной реализации железа?)
Мне кажется можно сделать issue на создание поля конфигурации для модуля драйверов, также добавить в него переименование (по разному функции зовутся и давайте уж звать низкий уровень lld =) ) и назвать его рефакторинг драйвера.
И еще один на создание дополнительных тестов для драйвера (подключиться могут все к написанию)

**Comment by KaiL4eK** [comment]
Задачи разбросаны? Эту задачу можно удалять?

**Comment by serykhelena** [comment]
Пока, наверное, закрывать нельзя... надо дождаться инфы от Дениса Михайловича, вроде он говорил на следующей неделе .. нужна конкретика в управлении существующим железом, возможно, всё придётся совсем поменять

**Comment by KaiL4eK** [comment]
Ладно, тогда переименую)

**Comment by KaiL4eK** [comment]
В настоящее время вроде инфа следующая: поворот на последовательном порте (хотя тут встает вопрос, замкнута ли система внутри платы Насти), ход на ЦАП, тормоз на ШИМ (мост соответственно).

**Comment by KaiL4eK** [comment]
Если инфа соответствует правде - нужно создавать отедльные задачи на доработку каждой из частей

**Comment by KaiL4eK** [comment]
Такс, что с этой задачей? Кажется 2 из 3х уже реализовано, может эту закроем и конкретно по рулю пойдем?

**Comment by serykhelena** [comment]
Мне нравится такая идея

**Comment by KaiL4eK** [comment]
Переход был очень плавный - коммит не указываю)
