### ISSUE TITLE
Переименовать функции в драйвере управления приводом

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#18]
Переименовать функции в соответствии с форматом lld... и слить ветки

**Comment by serykhelena** [comment]
Сделано

**Comment by KaiL4eK** [comment]
Коммит?

**Comment by serykhelena** [comment]
Yeap

**Comment by KaiL4eK** [comment]
Какой коммит?)

**Comment by serykhelena** [comment]
https://github.com/KaiL4eK/tigra_project/commit/4fdff56398924dbee59e847ded61f843701e865d
