### ISSUE TITLE
Добавить тесты для драйвера управления приводами 

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#19]

**Comment by KaiL4eK** [comment]
В bf303504 появился тестик, можно управлять им через Serial и постепенно менять значения (проценты)

**Comment by KaiL4eK** [comment]
Кажется тестик исчерпывающий, еще конечно можно прикрутить гуевый интерфейс, но это уже верх отладки)
Закрываю?

**Comment by serykhelena** [comment]
Закрывай (:

**Comment by KaiL4eK** [comment]
Таки закрываю)
