### ISSUE TITLE
Объединить перифирии для использования одного модуля АЦП

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#20]
Думаю, что имеет смысл использовать один модуль АЦП, но разные каналы

**Comment by KaiL4eK** [comment]
Такс, давай конкретнее, для каких задач?)

**Comment by serykhelena** [comment]
Для использования датчика положения руля и, видимо, датчика тормоза у тебя

**Comment by KaiL4eK** [comment]
Положение руля основывается на АЦП? Мы хотим использовать один модуль на разные задачи? Проблемой может стать вычленение данных для конкретных датчиков, так как в общем буфере они будут перемешаны

**Comment by serykhelena** [comment]
Я не уверена, но Нина мне так сказала ... окей, тогда беру другой модуль

**Comment by KaiL4eK** [comment]
На самом деле идея хорошая, надо только понять, как нам объединить и какие нужны функции чтобы забирать данные

**Comment by KaiL4eK** [comment]
Необходимо просто забирать данные из буффера? Тогда можно инициализировать и запустить преобразования по триггеру. И доп функция - получить значение.

**Comment by serykhelena** [comment]
Наверное, для начала - да, нужно просто забирать значения. Пока не очень понимаю, что ты имеешь в виду, но я подумаю...

**Comment by KaiL4eK** [comment]
Данный таск предлагаю оставить под вопросом, так как сейчас нет потребности в ужатии на остатки АЦП, еще, вроде, остался третий свободный

**Comment by KaiL4eK** [comment]
Начинает поджимать, задумываться еще рано? @serykhelena что у тебя со считыванием АЦП, тоже 10 мс?

**Comment by serykhelena** [comment]
Пока что - да, но Денис Михайлович ещё не высказывал свои пожелания (обычно предлагается 1 мс)

**Comment by DenF2412** [comment]
Есть мысль (поправьте меня, если она не корректная). Можно определить общую для всех частоту считывания сигналов (обычно берется наибольшая частота, например 1 кГц ;) ), контроллер раз в мс считывает все каналы и по окончанию процесса считывания производит некую обработку, если это необходимо, и раскидывает полученные и обработанные данные из буфера по глобальным переменным. Далее любой желающий может забрать нужную ему переменную, когда она ему потребуется.

**Comment by KaiL4eK** [comment]
Общий модуль запилен, ADC1 используется для датчиков тормоза и руля. Issue закрываю, если понадобится еще добавить - пойдет отдельно =)
