### ISSUE TITLE
Добавить тесты для драйвера датчиков руля

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#22]

**Comment by KaiL4eK** [comment]
А чем существующий тест не устраивает? Единственное, может вывод поменять, в остальном вроде норм. Или надо проверить какой-то функционал?

**Comment by serykhelena** [comment]
Не знаю, просто мне кроме этого пока в голову ничего не пришло. Может и не надо, про какой-то функционал тоже не знаю...

**Comment by KaiL4eK** [comment]
Просто вся сенсорика лежит на АЦП, можно конечно сделать тест, который взаимодействует с матлабом и строить графики, дабы проверить фильтрацию

**Comment by KaiL4eK** [comment]
Для руля Настя делает контур положения, стоит вопрос, нужно ли сильно заморачиваться над тестами, так как тут уже почти готовая система)

**Comment by serykhelena** [comment]
Предлагаю пока закрыть эту issue, так как скорее всего работа с приводом руля будет осуществляться по UART (если я правильно понимаю)
