### ISSUE TITLE
Разработка драйвера взаимодействия с УЗ-датчиками 

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#23]

**Comment by KaiL4eK** [comment]
Может есть ссылки на датчики?

**Comment by serykhelena** [comment]
https://www.maxbotix.com/Ultrasonic_Sensors/MB7070.htm 
https://www.maxbotix.com/Ultrasonic_Sensors/MB1200.htm

Вроде как эти два

**Comment by KaiL4eK** [comment]
Кажется, если #25 уже сделан, то этот уже точно в тестированных висеть должен)

**Comment by serykhelena** [comment]
Тест сделан, работает

**Comment by KaiL4eK** [comment]
Собстнна, #25 уже ведь сделан? Получается тут тоже тест на железе пройден?
