### ISSUE TITLE
Встраивание прослойки взаимодействия с системами верхнего уровня

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#24]
Будем ROS встраивать? =)

**Comment by serykhelena** [comment]
Я - за (мне кажется, это самое быстрое, что можно сделать....)

**Comment by KaiL4eK** [comment]
Во время встраивания была включена опция "-specs=nosys.specs" в Makefile к USE_OPT.

**Comment by KaiL4eK** [comment]
Реализовано с тестом без конфигурации на конкретные топики 39f4e1fef23e9f909fec4a675a3997159c157cd7
