### ISSUE TITLE
Дополнить драйвер по работе с УЗ-датчиками режимом синхронизации

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#25]
1. Настроить триггеринг таймера (события) для АЦП на 10 Гц
2. Для синхронизации настроить ШИМ (частот 10 Гц), ширина - 20 мкс (потому что даташит)

**Comment by KaiL4eK** [comment]
Может отписаться по результатам?) Вроде поставленные заачи выполнены?)

**Comment by serykhelena** [comment]
Синхронизация для 2-х датчиков работает

**Comment by KaiL4eK** [comment]
Так это же пройденные тесты на железе?) Можно переносить в колонку пройденных тестов?)
