### ISSUE TITLE
Проверить датчик Sharp 5m на работоспособность на улице (с солнышком)

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#26]
Датчик инфракрасный - надо проверить возможность работы на улице.

**Comment by KaiL4eK** [comment]
Надо больше тестов) пока проблемы только на глянцевой поверхности)

**Comment by serykhelena** [comment]
А можно поподробнее расписать тесты, какие именно нужно ещё сделать?

**Comment by KaiL4eK** [comment]
Имею ввиду еще при солнце ярком потестить)

**Comment by serykhelena** [comment]
Работают (=
