### ISSUE TITLE
[lld_control]: Типы данных в задании значений драйверов

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#29]
https://github.com/KaiL4eK/tigra_project/blob/ea2a2ef4bef07bae978a7ce74b1e51c1392657be/controller_driver/src/lld_control.c#L120
Не скажу, что это полноценная бага, но несет потенциально опасный характер. Если попробовать передать значения больше 255 (в некоторых 127), то биты будут обрезаны и не факт, что значения будут коректные. Рекомендуется использовать int32_t, ввиду использования 32х битного контроллера с большой памятью об экономии думать не приходится) Как на uint8_t, так и на int32_t процессор занимает один такт обработки)

**Comment by serykhelena** [comment]
@KaiL4eK  Но предполагается, что значение аргумента функции должно быть в диапазоне от 0 до 100 %, разве имеет смысл использовать int32_t в этом случае? Или может как-то ограничить вводимые значения...

**Comment by serykhelena** [comment]
Добавила ограничения на вводимые значения процентов для работы с приводами. Просьба посмотреть, целесообразно ли это (=

**Comment by KaiL4eK** [comment]
Ввод ограничить - правильно, проблема в передаче значений в функцию
Если кинуть на нее int16_t (управение может выходить за пределы), он урежет последние 8бит и в результате вместо 300 будет что-то не то

**Comment by KaiL4eK** [comment]
Установкой аргументам int32_t мы исключаем возможность нечаяно обрезать биты, если пользователь данной функции сам не учел ограничения (защита от дурака)
