### ISSUE TITLE
[lld_steer_sensors]: Что-то плохо с модулем

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#30]
https://github.com/KaiL4eK/tigra_project/blob/ea2a2ef4bef07bae978a7ce74b1e51c1392657be/controller_driver/src/lld_steer_sensors.c#L14

Возможно при слиянии произошла беда, в модуле снова появился АЦП, при этом также используется common_ADC1 реализация.

https://github.com/KaiL4eK/tigra_project/blob/ea2a2ef4bef07bae978a7ce74b1e51c1392657be/controller_driver/src/lld_steer_sensors.c#L79

Помимо этого - тут еще и сонары всплыли)

Надо бы разобраться, можно глянуть на изменения кода по коммитам и понять, что и как поправить)

**Comment by serykhelena** [comment]
Вроде теперь норм (= 9b7642bbccdc2ad16edf95af27ebfad1ce39d7a7
