### ISSUE TITLE
[lld_wheel_pos_sensor]: Лишний код в модуле

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#32]
Начиная с этого https://github.com/KaiL4eK/tigra_project/blob/f3656df5e906ef75ce46330d6b295e7319c0bdfc/controller_driver/src/lld_wheel_pos_sensor.c#L29
и все что касается SD - надо убрать, лишний функционал
Все, что необходимо для отладки рекомендуется реализовывать через функции и выводить через тесты.

**Comment by serykhelena** [comment]
Убрано (= 51818e8be30146fcf99bfeb699e51fd2c8e63dfa
