### ISSUE TITLE
[test_brake_unit_cs.c] Концевик сделать нормально замкнутым

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#33]
В нажатом состоянии - низкий уровень (0), в отпущенном - высокий уровень (1)

**Comment by KaiL4eK** [comment]
Это инфа от механики?

**Comment by serykhelena** [comment]
Да, сейчас Денис Михайлович и Андрей Николаевич устанавливают

**Comment by KaiL4eK** [comment]
Еще раз укажу коммит, но в issue уже указана ссылка 67aa083
