### ISSUE TITLE
[lld_control]: Функция направления руля

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#34]
https://github.com/KaiL4eK/tigra_project/blob/67aa0831d66c61a397c5323a950d30fa3533fe23/controller_driver/src/lld_control.c#L231
Не уверен, что данная функция понадобится, так как можно будет напрямую передавать положительное и отрицательное значение для направления.

**Comment by serykhelena** [comment]
Убрано dffe5a22f4c5656de2ebce5a81d4f5de3b022734
