### ISSUE TITLE
Драйвер резервного управления приводом руля

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#35]
В пятницу приедет ESC, для неё надо ШИМ (100 Гц) и функции с аргументами (заданием) от -100% до 100%

**Comment by serykhelena** [comment]
Сделано, функция lldControlSetSteerPower(..), нужно будет правильные коэффициенты пересчёта из % в скважность указать. dffe5a22f4c5656de2ebce5a81d4f5de3b022734

**Comment by KaiL4eK** [comment]
Так коэффициенты - это конфигурация? То есть найти пределы управления?

**Comment by serykhelena** [comment]
Да, именно (:
