### ISSUE TITLE
Конфигурация датчиков руля

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#42]
Надо найти пределы АЦП и преобразование в симметричный диапазон положения руля (-100:100). Предлагается использовать float с переименованием на имя датчика (typedef).

**Comment by serykhelena** [comment]
Диапазон 188 до 3885 примерно (единицытАЦП)

**Comment by KaiL4eK** [comment]
Это относительно 5В?
У нас же 3.3

**Comment by serykhelena** [comment]
Это уже 3.3. Я поставила делитель напряжения, поэтому STM-ка получает сигналы в диапазоне от 0 до 3.3 В

**Comment by KaiL4eK** [comment]
Коммит уже был?

**Comment by KaiL4eK** [comment]
Конфигурация сдалана на половину, остался несконфигурированным датчик тока

**Comment by KaiL4eK** [comment]
Вроде 2e29aff появилась подготовка к точной конфигурации, закрываю
