### ISSUE TITLE
Ограничение выхода датчика руля

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#44]
https://github.com/KaiL4eK/tigra_project/blob/d401ff1abbd73f1ca3eabe27ed17cf0adb35bc5b/controller_driver/src/steer_unit_cs.c#L44

Такое ограничение относится к самому датчику, а не к СУ. Возможно, вместе с масштабирование, имеет смысл разместить конфигурацию внутри модуля датчиков руля.

**Comment by DenF2412** [comment]
Думаю, что лучше всего привести рабочий диапазон датчика к -100 +100 (хотя и этот диапазон избыточен с учетом особенности механики рулевого привода).
Также стоит производить проверку значений АЦП на корректность. Если значения около нуля - авария (обрыв сигнального провода или питания датчика). Если значения выбиваются больше чем на N единиц выше максимального угла поворота или ниже минимального - предаварийная ситуация, необходима проверка механики и/или цепей питания датчика и делителя напряжения

**Comment by KaiL4eK** [comment]
Конфигурация вместе со связанными проверками сделаны в 72b7490
