### ISSUE TITLE
Имитация двойного нажатия пульта перехода в реверс

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#45]
https://github.com/KaiL4eK/tigra_project/blob/d401ff1abbd73f1ca3eabe27ed17cf0adb35bc5b/controller_driver/src/steer_unit_cs.c#L66

Хитрая реализация имитации, вероятно, относится не к СУ, а к самому заданию управления, так как при замене ESC на, например, драйвер имитация более не потребуется.

Также просьба кратко описать логику имитации.

**Comment by KaiL4eK** [comment]
Интересует, конкретно, почему задана следующая последовательность (возьмем дискрету 10мс):
150мс / задание нулевого значения
50мс / задание отрицательного
100 мс / задание нулевого значения
700 мс / задание отрицательного значения
После этих симуляций - задание значения как оно есть

**Comment by KaiL4eK** [comment]
https://github.com/KaiL4eK/tigra_project/blob/d401ff1abbd73f1ca3eabe27ed17cf0adb35bc5b/controller_driver/tests/test_steer_unit_cs.c#L55

А теперь вопрос к тесту - почему `Sleep` за пределами `while ( 1 )`?
Получается, задание проскакивает без задержек? При этом вычислительная скорость достаточно высока и большое количество заданий ШИМ не имеет силы, так как период одного импульса ШИМ еще не закончился.

**Comment by DenF2412** [comment]
По последовательности действий: 
При работе с пульта управления (радиоуправления) при переходе с движения вперед на движение назад ESC реверс не включает, для движения в обратную сторону нужно отпустить курок в нейтральное положение и снова нажать для движения назад.
Также экспериментально было выяснено, что esc не всегда отрабатывает реверс, если сразу после нуля дать -100 (почему так, вопрос открытый, тк вперед такой проблемы ни разу не было...).
Поэтому, если сигнал управления от регулятора переходит через ноль, а именно из положительной области в отрицательную, мы имитируем двойное нажатие курка.
Последнее действие в имитации обусловлено проблемой с резким переходом 0 -100.
Промежутки времени мы подбирали экспериментально.

**Comment by KaiL4eK** [comment]
Логика понятна, при этом на форумах пишут, что первый переход на отрицательную область включает тормоз, далее переход на ноль и после этого снова на реверс уже переводит ESC на работу в обратную сторону. 
Предлагаю тогда во вторник проработать этот момент, так как в совокупности с вопросами по тесту появляется множество вопросов по тому, были ли фиксы после коммита, или же действительно получалось так, что между итерациями `while ( 1 )` нет задержки.

**Comment by KaiL4eK** [comment]
Одна из ссылок на принцип работы: https://www.rcgroups.com/forums/showpost.php?p=22344816&postcount=4

**Comment by KaiL4eK** [comment]
Еще одна: https://www.raspberrypi.org/forums/viewtopic.php?t=63932

**Comment by KaiL4eK** [comment]
Перенесено и проверено в 6fe19f4
