### ISSUE TITLE
Разработка теста подачи питания на рулевой привод

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#47]
Данный тест планируется использовать в рабочем режиме, предлагается сделать функцию, которая проверяет способность ESC подавать питание на привод.
Логика в общих чертах:
- Подать малое питание на привод (Задать малый уровень ШИМ)
- Проверить значение датчика тока руля
- Проверить превышение значения тока заданного порога (по факту отсутствие контакта - выключенный ESC не приведет к росту тока вообще)

**Comment by serykhelena** [comment]
3a660953adf9a6a8a0f30504e7d9791c457e8dbf Нужно тестить...

**Comment by KaiL4eK** [comment]
Прадлагается перенести `testSteerPoweredStatus()` в модуль `lld_control`, так как по задумке тест не является тестом =)
По факту сама функция должна возвращать булево значение, говорящее о подключении ESC (состояние вкл/выкл)
- Назвать предлагается `lldControlSteerIsEnabled()`
- Важно отметить в комментариях к прототипу, что функция имеет задержки внутри и не должна вызываться внутри цикла управления
- В самом тесте `testSteerPoweredStatus()` можно с периодичностью пол секунды вызывать тест и выводить его результаты

**Comment by serykhelena** [comment]
@KaiL4eK если будет возможность, посмотри, пожалуйста, по коду - то ли это, что нужно. И может быть вывод по UART как-то по-другому оформить, но пока в голову ничего лучше не пришло (= На этом issue закрываю, скоро открою issue по тестированию этого фнукционала

**Comment by KaiL4eK** [comment]
Все сделано отлично, в соответствии с предложениями)
Я плохой совет дал с точки зрения абстракции, сейчас получается, что в lld_control изпользуется lld_steer_sensors, что является плохой привязкой

**Comment by KaiL4eK** [comment]
В целом по логике - можно проверять не каждое значение, а накопить и в конце проверить среднее
Также заметил, что не хватает задержки между считываниями датчика

**Comment by KaiL4eK** [comment]
По поводу абстракции, полагаю есть смысл перенести функцию в модуль системы управления рулем, там использование низкоуровневых функций оправдано

**Comment by serykhelena** [comment]
Да, между считываниями нет... но конечное значение флага формируется, только после прогонки 500 тиков.. в функции lldControl SteerIsEnable()..Наверное, нужно поаккуратнее с задержками (=

**Comment by KaiL4eK** [comment]
Все верно, только результат формируется не по результатам 500 итераций, а по каждой итерации, меняя каждый раз флаг
Задержка здесь будет оправдана, так как необходимо в комментариязх к прототипу написать о требовании вызывать данный тест вне управления (вначале, например)
И все таки из-за нарушения абстракции предлагаю перенос функции (с переименованием) в модуль СУ - открываю issue обратно

**Comment by KaiL4eK** [comment]
https://github.com/KaiL4eK/tigra_project/blob/024b6d2ae7a388fb1758f81121e2b469362808ae/controller_driver/src/lld_control.c#L304

Этот кусочек можно заменить возвратом самого флага

**Comment by serykhelena** [comment]
Получается мне внутри функции проверки нужно использовать счётчик и while по условию этого счётчика, типа делай 500 раз считывание датчика и накопление значения с задержкой 10 мс. Но как же возвращать bool значение в конце... например, берём 5 считываний: 1 + 1 + 0 + 1 + 1 = 4 -> 4/5 = 0.8 ??

**Comment by KaiL4eK** [comment]
Берем среднее, как и представлено, сравниваем с порогом, выше порога (true) или ниже (false)
рекомендую счетчик сделать 100 вместо 500, секунды на тест, думаю, хватит
```
int32_t cntr = 0;
int32_t accum = 0;
int32_t tickAmount = 100;
while ( cntr < tickAmount )
{
    accum += getCurrentValue();
    sleep ( 10 );
}

accum /= tickAmount;
return (accum > threshold);
```

**Comment by KaiL4eK** [comment]
Не забываем, что значения тока в процентах, представленный код работает только для правильного подключения фаз
Таким образом тест выдаст false для неверного подключения фаз
И не забыть написать комментарий (note) о том, что тест включает цикл и задержку

**Comment by serykhelena** [comment]
Тогда отдельный тест излишен, я его убираю?

**Comment by KaiL4eK** [comment]
Почему излишен?

**Comment by KaiL4eK** [comment]
Коммит хороший)

**Comment by serykhelena** [comment]
Тест оставила, но не уверена в его внутренностях. Функцию переместила в steer_unit_cs.c

**Comment by KaiL4eK** [comment]
Тест можно оставить - полезный
По фиксам теста мысли:
- Заменить отдельную инициализацию control и sensors на cs_init (включает оба)
- Разместить вызов теста внутри while и вызывать его без задержек (внутри него и так секунда задержки)
- Вывод инфы норм - просто выводить результат теста
- Можно еще добавить функционал включения/выключения вызова `isEnabled` - например на символ 1 вызывать тест (обернуть флагом включено), на символ 2 - тест не вызывать (сбросить флаг), а на обмотки руля подать 0 (чтобы не греть)

**Comment by KaiL4eK** [comment]
Пара моментов по тесту)
- Под cs_init имел ввиду `steerUnitCSInit()` =) Впредь буду точнее описывать)
- На данный момент в тесте функция `isEnabled` вызывается только если набран символ 1
- Предлагался вариант похожий на следующий:
```
char symb = sdGetTimeout();
if ( symb == '1' )
    // set check flag true
else if ( symb == '2 )
    // set check flag false

if ( check_flag )
{
    // call isEnabled test + chprintf
}
else
{
    // disable PWM
}
```

**Comment by serykhelena** [comment]
@KaiL4eK  на счёт steerUnitCSInit я так тебя и не поняла .... ведь такая функция уже есть, и вроде как ты просил из неё объединить две инита в другую функцию? Или я неверно поняла тебя? (=

**Comment by KaiL4eK** [comment]
Ха-ха, коммент в зачет, закрываем)

**Comment by KaiL4eK** [comment]
Хотя стоп, щас инит вообще куда-то пропал =)

**Comment by KaiL4eK** [comment]
Да, я и предлагал ее использовать) `steerUnitCSInit`

**Comment by KaiL4eK** [comment]
Сейчас тоже хорошо выглядит, правда)
Инит бы только, а то тест не запустится =)

**Comment by serykhelena** [comment]
Согласна, косяк (= "Щазззз" всё будет (=

**Comment by KaiL4eK** [comment]
Коммит и закрывай =)

**Comment by serykhelena** [comment]
Уиииии, Халк хочет закрывать!!!
