### ISSUE TITLE
Разработка драйвера ручки тормоза

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#5]
Если сегодня я правильно понял - в ручке тормоза есть лишь концевик. При этом от данной ручки необходимо асинхронное поведение для наших задач, что делает ее отличным кандидатом для отдельного низкоуровневого драйвера.

**Comment by KaiL4eK** [comment]
Правильно ли все определено?

**Comment by DenF2412** [comment]
@KaiL4eK да, все верно
Сигнал с концевика переводит систему в режим ручного управления.

**Comment by KaiL4eK** [comment]
Реализовано в 631cfc7. Тест переключает состояние диода по фронту на привязанном пине. Реализация переключения в состояние ручного управление будет в отдельной issue. На данный момент реализация асинхронно в ISR контексте вызывает переданную функцию.

**Comment by KaiL4eK** [comment]
Ах да, надо будет проверить сигнал данной ручки)
