### ISSUE TITLE
Испытания системы управления рулевым механизмом

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#50]
https://github.com/KaiL4eK/tigra_project/blob/2e29affad7a43e871b4ffa88690490c0a871cd0f/controller_driver/src/steer_unit_cs.c#L5

Много изменений с последнего теста появилось, надо протестировать новые фиксы и настроить регулятор.

**Comment by serykhelena** [comment]
f2151621b2777f871a24dedac1b57490ec12ed68 Сделана первоначальная настройка регулятора, возможно, нужно будет немного подправить коэффициенты, но это надо уже в процессе движения тигры делать

**Comment by serykhelena** [comment]
Система работает с новыми фиксами
