### ISSUE TITLE
Тестирование функционала подачи питания на рулевой привод

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#52]

**Comment by KaiL4eK** [comment]
Теперь реально надо проверить и понять, какой порог и может стоит побольше ШИМ подать

**Comment by KaiL4eK** [comment]
Короче конфиг настроить =)

**Comment by KaiL4eK** [comment]
Вроде на момент поездки было все адекватно, закрываем?)

**Comment by serykhelena** [comment]
Я за (:
