### ISSUE TITLE
Добавить управление освещением

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/tigra-project#53]
Встроить в систему управления (либо как-то иначе) изменение уровней дискретных выходов, позволяющих осуществлять индикацию светом (поворотники, стоп-огни)

**Comment by KaiL4eK** [comment]
Есть вариант добавить в каждый ответственный модуль (тормоз, руль) свои выводы и соответственно реализовывать индикацию)

**Comment by serykhelena** [comment]
Под ответственным модулем ты подразумеваешь функцию, .с-файл? Просто меня немного смущает, что например, реализация поворотников требует задержки между изменениями состояний лап. Я думала сделать это через счётчик, но тогда это нужно внедрять прямо в систему управления (например)

**Comment by KaiL4eK** [comment]
Оу, а что за задержка? Тут поподробнее, я не в курсе)

**Comment by KaiL4eK** [comment]
Да все верно, обычно модулем называется .с файл (один из вариантов разбиения)

**Comment by serykhelena** [comment]
Ну, например, чтобы человек мог видеть, как мигают поворотники, нужно чтобы между сменой уровней была, например, 1 с

**Comment by KaiL4eK** [comment]
аа, ты имеешь ввиду то, что поворотники не горят сплошным цветом, а мигают?

**Comment by serykhelena** [comment]
Да, да, именно

**Comment by KaiL4eK** [comment]
Ну, например, можно сделать модуль, в котором будет вертеться один поток, который будет просто следить за состоянием переменных (или битовой маски) и переводить состояния ножек.
Можно использовать ШИМ каналы и просто переключать между включен ШИМ (50% скважности) и выключен. Аналогично с первой идеей - в отдельном потоке, который связан с остальными через переменные.

**Comment by serykhelena** [comment]
Таккк... это мне нужно осознать... а тот факт, что включение освещения зависит от значения управляющего сигнала, который рассчитывается совсем в другом модуле..это ничего? в том смысле, они увидят друг друга..то? (=

**Comment by KaiL4eK** [comment]
Тут скорее вопрос, на что мы хотим завязаться. Если мы мигаем конкретным поворотником в ситуации, когда значение датчика перешло какой-то порог, то мы как-бы завязываемся на датчик и в модуле системы управления, получая сигнал с датчика, можем оценить и установить тот или иной мигалку функцией типа `lightsSetBlinking( RIGHT )`. Внутри нее она просто устанавливает переменную, которую прочитает поток мигалок и выставить необходимые ноги.

**Comment by KaiL4eK** [comment]
или вообще, можно установить `enum`, который будем передавать в функцию `lightsSetState( state )` состояние.
`enum` может состоять из состояний:
- LIGHTS_TURN_RIGHT
- LIGHTS_TURN_LEFT
- LIGHTS_TURN_BRAKE
- LIGHTS_MOVE_FRWRD
- LIGHTS_MOVE_BCKWRD
В результате внутри потока мигалок будут устанавливаться те или иные включения/выключения

**Comment by KaiL4eK** [comment]
А установка состояний, например FRWRD будет отменять состояния LEFT и RIGHT, если те были установлены ранее
То есть настроится база правил, что одно состояние отменяет другое (-ие)

**Comment by KaiL4eK** [comment]
не уверен, что правильно завязываться на сигнал задания, хотя и так можно)

**Comment by serykhelena** [comment]
Денис Михайлович предлагает всё же по сигналу управления, потому что поворотник нужен для того, чтобы показать намерение поворота, а не факт того, что поворот уже происходит. Лёш, я правильно понимаю, что в функции `lightsSetState( state)` я в переменную записываю состояние из enum. Потом относительно сигнала управления - меняю эту переменную на другое состояние. Также делаю несколько потоков, в которых исходя из условия мы что-то делаем ...???

**Comment by serykhelena** [comment]
@KaiL4eK  посмотри, пожалуйста, как будет возможность, можно ли так вообще делать (=

**Comment by KaiL4eK** [comment]
Да, основная идея такая, только пару моментов:
- Может быть побольше задержку (таки 10-20 мс хотя бы, хотя это дело вкуса)
- https://github.com/KaiL4eK/tigra_project/blob/33d994916b5fef8de7675fb5b460c7a0ebd77787/controller_driver/src/light_unit.c#L116
Здесь основная задумка была просто в передаче состояния переменной (то еть функция из одной строки =)), а принятие решения, что включать реализовывать на месте внутри систем управления
Да и сейчас по значению не понятно, что означает controlSignal, мне кажется проще вынести все пороги и решения за эту функцию в место использования ее (СУ)
Также, enum надо сделать публичным, чтобы внешние модули могли его использовать)

**Comment by KaiL4eK** [comment]
>  Лёш, я правильно понимаю, что в функции lightsSetState( state) я в переменную записываю состояние из enum. 

Вот именно про это я в последнем комменте и расписал)

**Comment by serykhelena** [comment]
Я думала эту функцию `void lightsSetState( int32_t controlSignal ) ` использовать в CS по рулю.... это не вызовет дополнительных задержек? Ведь потоки сами должны разобрать, нет? 
И ещё...я сейчас убрала ШИМ и вернулась к pal, потому что мне нужна настройка ножек на opendrain... возможно, для ШИМ тоже можно было такую настройку сделать...не знаешь случайно ? (=

**Comment by serykhelena** [comment]
В общем, что-то я запуталась....
А как сделать enum публичным? О_о

**Comment by KaiL4eK** [comment]
В заголовок засунуть

**Comment by KaiL4eK** [comment]
> Я думала эту функцию void lightsSetState( int32_t controlSignal ) использовать в CS по рулю.... это не вызовет дополнительных задержек? Ведь потоки сами должны разобрать, нет?

Ну помимо поворота есть же еще и лампочки "Стоп"?
И причем тут задержки?

**Comment by KaiL4eK** [comment]
> возможно, для ШИМ тоже можно было такую настройку сделать...не знаешь случайно ? (=

Может быть, вместе с Alternate поставить еще и Opendrain?

**Comment by serykhelena** [comment]
Лампочки Стоп, наверное, должны зависеть от тормоза, в общем, я тут посидела и поняла, что мне не совсем понятно по каким событиям они должны зажигаться, нужно ловить ДМ для этого...  Честно говоря, я хотела в CS для руля перед функцией `lldControlSetSteerPower` поставить `lightsSetState` и всё.... Я сейчас скину коммит....удобно посмотреть?

**Comment by KaiL4eK** [comment]
Давай попробуем) Идея в том, что много менять не надо) Сейчас внутри этой функции у тебя стоит
https://github.com/KaiL4eK/tigra_project/blob/33d994916b5fef8de7675fb5b460c7a0ebd77787/controller_driver/src/light_unit.c#L119
Я же предлагаю это поставить внутрь CS, и будет что-то типа
```
    if( controlSignal <= -20 )
    {
        lightsSetState( LIGHTS_TURN_LEFT );
    }
```
А Сама функция `lightsSetState()` просто устанавливает глобальную переменную

**Comment by KaiL4eK** [comment]
https://github.com/KaiL4eK/tigra_project/blob/db7e06597ddf76fb8c6d5ebc00b6511362c4c8f2/controller_driver/src/light_unit.c#L40

Нееееееет....
Это же зависон для потока...)

**Comment by serykhelena** [comment]
Да...фигня какая-то....согласна .

**Comment by serykhelena** [comment]
То есть, если у меня сейчас 3 правила - нужно 3 потока?

**Comment by KaiL4eK** [comment]
Ну, можно и на одном сделать)

**Comment by KaiL4eK** [comment]
Просто с использованием счетчиков и масок, сейчас попробую коммитнуть

**Comment by serykhelena** [comment]
Стооооооооооооййййййййййййй

**Comment by KaiL4eK** [comment]
> Стооооооооооооййййййййййййй

??

**Comment by serykhelena** [comment]
Извини, поторопилась (= Коммить (=

**Comment by KaiL4eK** [comment]
https://github.com/KaiL4eK/tigra_project/blob/33d994916b5fef8de7675fb5b460c7a0ebd77787/controller_driver/src/steer_unit_cs.c#L86
А вот после этой строки можно добавить установку поворотника)

**Comment by KaiL4eK** [comment]
И не забудь тест написать для него, можно разместить в тесте tigra_project/controller_driver/tests/test_lightning.c

**Comment by serykhelena** [comment]
Вроде есть уже тест..но я сейчас посмотрю все изменения, возможно, тест надо будет исправить..

**Comment by KaiL4eK** [comment]
Ага, я только посмотрел в него) ну тогда в соотетствии с тем, что сейчас задается не control, а state, можно повключать разные режимы с задержкой)

**Comment by KaiL4eK** [comment]
Или на каждую букву поставить свой режим)

**Comment by KaiL4eK** [comment]
Полагаю, можно закрвать?)

**Comment by serykhelena** [comment]
В общем-то да (:
