### ISSUE TITLE
Разработка контура скорости привода хода (акселерация)

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#6]
Вот и первая задача из уровня повыше - контур скорости с необходимыми ограничениями задающего значения + своим законом управления. Пока можно заложиться на акселерацию, так как для десселерации (замедления) нужно будет использовать модуль привода тормоза.

**Comment by KaiL4eK** [comment]
Дальнейшая модификация описана в #15. @TatianaEtu ты берешь эту задачу?

**Comment by TatianaEtu** [comment]
Да

**Comment by KaiL4eK** [comment]
@TatianaEtu также в реализации просьба предусмотреть ограничения входа (задания по скорости), которые можно конфигурировать.

**Comment by TatianaEtu** [comment]
У меня возник вопрос, направление движения должно изменяться, когда изменяется знак скорости? Т.е. задающее воздействие по скорости изменяется в диапазоне [-Vmax; +Vmax] или [0; +Vmax]?

**Comment by KaiL4eK** [comment]
Как мне кажется, вход данной системы должен ограничивать пределы симметрично, регулировка переключений тормоз/газ уже является внутренней системой данного контура, поэтому просто вход системы стоит ограничить [-Vmax; +Vmax] 
Хотя может быть несимметрично стоит сделать, так как сдавать назад с такой же максимально скоростью не всегда требуется

**Comment by KaiL4eK** [comment]
Название ветки просьба называть без скобок)
Желательно еще и через формат `branch_name` (подчеркивания)

**Comment by KaiL4eK** [comment]
Лейбл вопроса еще актуален?

**Comment by TatianaEtu** [comment]
Спасибо, лейбл снимаю)

**Comment by KaiL4eK** [comment]
Что-то есть в e2686eb7, ждемс тесты)
