### ISSUE TITLE
Разработка системы управления приводом тормоза

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#7]
Не берусь называть задачу разработкой контура, так как в нее будет включен концевик из датчиков привода тормоза.
Необходимо сделать (предварительно все уточнив) систему, которая позволяет задавать торможение колеса хода.
Берется в расчет тот факт, что при работе система ориентируется на контур тока через датчик. При отпускании цилиндр должен дойти до концевика и остановиться.

**Comment by DenF2412** [comment]
@KaiL4eK  один из вариантов алгоритма реализации:
Контур замыкается по скорости.
Давим до тех пор, пока не достигли заданной скорости или остановки, если заданная скорость равна нулю.
Контур тока позволяет ограничить максимальное значение потребляемого тока за счет ограничения максимально возможного задающего воздействия со стороны контура скорости. Однако при движении на опускание тормоза, необходимо ориентироваться на концевик, чтобы не создавать больших механических усилий на конструкцию там, где это абсолютно не нужно. 
Возможно в следующей версии САУ торможением будет оправдано использование нечеткой логики.

**Comment by KaiL4eK** [comment]
@DenF2412 по достижении концевика достаточно снять напряжение с обмотки или необходимо поддерживать удерживающий момент?

**Comment by DenF2412** [comment]
@KaiL4eK достаточно снять напряжение,двигающее привод в сторону концевика,  усилий как раз по достижению концевика прикладывать никаких не нужно

**Comment by KaiL4eK** [comment]
Какой датчик тока будем пользовать? ACS172?

**Comment by KaiL4eK** [comment]
Соответственно, 01be0d6 что-то готовое, посмотрим что решим на встрече по реализации)

**Comment by KaiL4eK** [comment]
Соответственно, ПИ-регулятор в вакуме сделан, ждем железа

**Comment by KaiL4eK** [comment]
Тут даже протестили систему управления) e4b023c2bbcbeaa07cdf9fba374be671f9056f6c
