### ISSUE TITLE
Проверить на реальном GPS топик fix_velocity, есть ли там информация о направлении модуля?

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/tigra-project#94]
Есть подозрение, что топик хранит инфу с магнитометра внутри. Надо понять, можем ли мы ее использовать.

**Comment by adhelll** [comment]
Для связи с реальным GPS приходится перезапускать его - отключать от COM порта и подключать снова. В таком случае GPS подключается, иначе выходит ошибка "Could not configure serial baud rate".
